name: Deploy

# Trigger the workflow on push and
# pull request events on the production branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: "cd /www/wwwroot/botadmin.tunagood.site &&
#!/bin/bash &&
set -e &&

echo "Deployment started ..." &&

# Enter maintenance mode or return true
# if already is in maintenance mode
(php artisan down) || true  &&

# Pull the latest version of the app
git pull origin main  &&

# Install composer dependencies
composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&

# Clear the old cache
php artisan clear-compiled &&

# Recreate cache
php artisan optimize &&

# Compile npm assets
npm run build &&

# Run database migrations
php artisan migrate --force &&

# Exit maintenance mode
php artisan up &&

echo "Deployment finished!"
